version: 2
updates:
- package-ecosystem: "docker"
  directory: "/compose/local/django"
  open-pull-requests-limit: 10
  schedule:
    interval: "daily"

- package-ecosystem: "docker"
  directory: "/compose/local/docs"
  open-pull-requests-limit: 10
  schedule:
    interval: "daily"

- package-ecosystem: "docker"
  directory: "/compose/local/postgis"
  open-pull-requests-limit: 10
  schedule:
    interval: "daily"

- package-ecosystem: "npm"
  directory: "/"
  open-pull-requests-limit: 10
  schedule:
    interval: "daily"

- package-ecosystem: "pip"
  directory: "/requirements"
  open-pull-requests-limit: 10
  schedule:
    interval: "daily"

- package-ecosystem: "github-actions"
  directory: "/.github/workflows"
  open-pull-requests-limit: 10
  schedule:
    interval: "daily"
